# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cuxambe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_c2d4d4d7e59d4600a6590a259cf4f6f8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3dc4338909b64745b37fbe93b723a32f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_c2d4d4d7e59d4600a6590a259cf4f6f8 }}/appsvc/cuxambe:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cuxambe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bc9607f166e647808b4c11527e920be8 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_c2d4d4d7e59d4600a6590a259cf4f6f8 }}/appsvc/cuxambe:${{ github.sha }}'